### ISSUE TITLE
Dropdown list takes a long time to load

### ISSUE THREAD

**Issue by camillobruni** [catapult-project/catapult#2642]
For V8 RuntimeStats we upload a huge number of different values for each run resulting in up to 30s load time for the subtest dropdowns.

With each run we currently upload  1 Bot × 270 Runtime Stats Categories × 2 Units × 28 Pages × 2 Configurations = roughly 30k Entries. Currently this only affects our x64 bot, but this is likely to be extended.
## Steps to reproduce
1. Log into https://chromeperf.appspot.com/report with your chromium account
2. Select the "v8" test suite and then choose the "x64" bot 
3. Wait (34 seconds on my desktop machine) for post request https://chromeperf.appspot.com/list_tests  (content-length: 46814)

**Comment by anniesullie** [comment]
@Apeliotes -- easy fix is to fix #2305. Since you're simplifying these menus, you may also consider just splitting each submenu into a separate XHR.

**Comment by anniesullie** [comment]
We fixed the issue #2305 with caching the dropdown contents, so you should see it load faster the second+ time it loads. I'm leaving this open since @Apeliotes is rewriting the menus based on a lot of user feedback, and may make further improvements that don't depend on caching.

**Comment by camillobruni** [comment]
nice! thanks a lot :+1:

**Comment by camillobruni** [comment]
This seems to have been only partially fixed. As of 2016-12-20 we started pushing another Runtime Call Stats benchmark to chromeperf, essentially adding a third more data points.

Thanks to your intervention yesterday, the graphs of existing reports just load fine again, but the dropdown on v8/x64 is still timing out.

**Comment by eakuefner** [comment]
Again stealing this from @Apeliotes -- fixing this will come as part of the work I am doing on #2830.

**Comment by anniesullie** [comment]
I'm duping this into #2642 where it is being actively worked on.

**Comment by perezju** [comment]
Annie, did you mean to close this issue as well? Or you meant to dupe against another issue?

**Comment by anniesullie** [comment]
Apologies, this is a dupe of #2387
