### ISSUE TITLE
HistogramSet - Fails merging

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4066]
https://logs.chromium.org/v/?s=chrome%2Fbb%2Fchromium.perf.fyi%2FHistogram_Pipeline_Linux_Perf%2F7980%2F%2B%2Frecipes%2Fsteps%2Floading.desktop_Dashboard_Upload%2F0%2Fstdout

```
Traceback (most recent call last):
  File "/b/c/b/Histogram_Pipeline_Linux_Perf/src/third_party/catapult/tracing/bin/add_reserved_diagnostics", line 91, in <module>
    sys.exit(main())
  File "/b/c/b/Histogram_Pipeline_Linux_Perf/src/third_party/catapult/tracing/bin/add_reserved_diagnostics", line 57, in main
    'name', 'storyTags', 'stories'))
  File "/b/c/b/Histogram_Pipeline_Linux_Perf/src/third_party/catapult/tracing/tracing/value/merge_histograms.py", line 29, in MergeHistograms
    js_args=[os.path.abspath(json_path)] + list(groupby))
  File "/b/c/b/Histogram_Pipeline_Linux_Perf/src/third_party/catapult/third_party/vinn/vinn/_vinn.py", line 188, in RunFile
    return _RunFileWithD8(temp_boostrap_file, js_args, v8_args, stdout, stdin)
  File "/b/c/b/Histogram_Pipeline_Linux_Perf/src/third_party/catapult/third_party/vinn/vinn/_vinn.py", line 267, in _RunFileWithD8
    'Exception raised when executing %s:\n%s' % (js_file_path, out))
RuntimeError: Exception raised when executing /tmp/tmpjAwidI/_tmp_boostrap.js:
/tracing/value/diagnostics/diagnostic_map.html:191: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
            this.get(tr.v.d.RESERVED_NAMES.MERGED_FROM)) {
                 ^
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Map.mergeRelationships (/tracing/value/diagnostics/diagnostic_map.html:191:18)
    at HistogramSet.mergeRelationships (/tracing/value/histogram_set.html:405:26)
    at eval (/b/c/b/Histogram_Pipeline_Linux_Perf/src/third_party/catapult/tracing/tracing/value/merge_histograms_cmdline.html:80:20)
    at Object.loadHTMLFile (/b/c/b/Histogram_Pipeline_Linux_Perf/src/third_party/catapult/third_party/vinn/vinn/html_imports_loader.js:140:5)
    at /b/c/b/Histogram_Pipeline_Linux_Perf/src/third_party/catapult/third_party/vinn/vinn/d8_bootstrap.js:151:19
```

**Comment by simonhatch** [comment]
Fixed?

**Comment by eakuefner** [comment]
This isn't fixed, but appears to be the same root cause as #4099 -- going to dupe.
