### ISSUE TITLE
[📍] Unable to find histograms for v8 benchmark

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#4323]
https://pinpoint-dot-chromeperf.appspot.com/job/17d424b2440000
https://pinpoint-dot-chromeperf.appspot.com/job/11a50862440000
https://pinpoint-dot-chromeperf.appspot.com/job/14ef755a440000
https://pinpoint-dot-chromeperf.appspot.com/job/15cf105a440000
https://pinpoint-dot-chromeperf.appspot.com/job/12d17072440000
https://pinpoint-dot-chromeperf.appspot.com/job/111b9292440000
https://pinpoint-dot-chromeperf.appspot.com/job/14e9000a440000
https://pinpoint-dot-chromeperf.appspot.com/job/151a5f6c440000
https://pinpoint-dot-chromeperf.appspot.com/job/14e134ea440000
https://pinpoint-dot-chromeperf.appspot.com/job/13adbb2a440000
https://pinpoint-dot-chromeperf.appspot.com/job/17b24e62440000

```
Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-cb921dd3.408121823305092534/dashboard/pinpoint/models/quest/execution.py", line 99, in Poll
    self._Poll()
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-cb921dd3.408121823305092534/dashboard/pinpoint/models/quest/read_value.py", line 240, in _Poll
    raise ReadValueError('Could not find values matching: %s' % name)
ReadValueError: Could not find values matching: histogram: v8-gc-latency-mark-compactor tir_label: browse_social story: browse:social:facebook
```

**Comment by dave-2** [comment]
It's looking for `v8-gc-latency-mark-compactor`, but the histograms json contains `v8-gc-latency-mark-compactor_percentage_in_v8_execute`

**Comment by simonhatch** [comment]
@eakuefner Hey Ethan this is exactly the same thing we were trying to find the other day in the histograms vs chartjson diff, is that fixed now?

**Comment by eakuefner** [comment]
Yes, this ought to have been fixed by https://chromium-review.googlesource.com/c/catapult/+/946631.

**Comment by simonhatch** [comment]
@eakuefner I think this is still happening, #4333 has a bunch of failed jobs unable to find the correct v8 histogram, and these were on ranges well after the fix landed on Mar 2 (the ranges were for Mar 6).

@psmarshall

**Comment by dave-2** [comment]
It looks like the Catapult roller got stuck, so fix was rolled in Chromium on Mar 7.
https://chromium.googlesource.com/chromium/src/+/a08dc477b554bb564bc861567a54c1f88ced57a2

**Comment by eakuefner** [comment]
Just dug into this. I had a hunch that something funky happened around the time this CL landed, so I wondered if maybe there was an abnormal delay getting it rolled into Chromium. Turns out that yes, the roll was blocked for several days, and the CL that fixed this bug only rolled into Chromium on March 7: https://chromium-review.googlesource.com/c/chromium/src/+/951671.

For future reference, the commit position of this roll is 541414, so if a Pinpoint job has a start that precedes that, it may fail with this bug.
